 root:
    id: "frame"
    model: "machine/frame.stl"
    type: "table"
    position: [0, 0, -30, 0, 0, 0]
    origin: [0, 0, 0]
    axis: null
    joint: null
    saddle:
        id: "saddle"
        model: "machine/saddle.stl"
        type: "linear"
        position: [0, -0, -21.5, 0, 0, 0]
        origin: [0, 0, 0]
        axis: "y"
        joint: 1
        table:
            id: "table"
            model: "machine/table.stl"
            type: "linear"
            position: [0, -5, -18.5, 0, 0, 0]
            origin: [0, 0, 0]
            axis: "x"
            joint: 0  
            a_axis:
               id: "a_axis"
               model: "machine/a_axis.stl"
               type: "angular"
               position: [-15.75, -5, -10, 0, 0, 0]
               origin: [0, 0, 0]
               axis: "a"
               joint: 3
               c_axis:
                  id: "c_axis"
                  model: "machine/c_axis.stl"
                  type: "angular"
                  position: [0, -5, -10, 0, 0, 0]
                  origin: [0, 0, 0]
                  axis: "c"
                  joint: 4

    headstock:
        id: "headstock"
        model: "machine/headstock.stl"
        type: "linear"
        position: [0, -1.5, 7.6, 0, 0, 0]
        origin: [0, 0, 0]
        axis: "z"
        joint: 2
    